// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/device","id":"1"},"2":{"path":"/device","name":"设备管理","icon":"mobile","redirect":"/device/list","id":"2"},"3":{"path":"/device/list","name":"设备列表","parentId":"2","id":"3"},"4":{"path":"/device/control/:id","name":"远程控制","hideInMenu":true,"parentId":"2","id":"4"},"5":{"path":"/data","name":"数据采集","icon":"database","id":"5"},"6":{"path":"/data/list","name":"数据列表","parentId":"5","id":"6"},"7":{"path":"/data/visualization","name":"数据可视化","parentId":"5","id":"7"},"8":{"path":"/data/detail/:id","name":"数据详情","hideInMenu":true,"parentId":"5","id":"8"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__device__list__index" */'@/pages/device/list/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__device__control__index" */'@/pages/device/control/index.tsx')),
'5': React.lazy(() => import('./EmptyRoute')),
'6': React.lazy(() => import(/* webpackChunkName: "p__data__list__index" */'@/pages/data/list/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__data__visualization__index" */'@/pages/data/visualization/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__data__detail__index" */'@/pages/data/detail/index.tsx')),
},
  };
}
