// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","name":"登录","layout":false,"id":"1"},"2":{"path":"/","id":"2"},"3":{"path":"/device","name":"设备管理","icon":"mobile","redirect":"/device/list","parentId":"2","id":"3"},"4":{"path":"/device/list","name":"设备列表","parentId":"3","id":"4"},"5":{"path":"/device/control/:id","name":"远程控制","hideInMenu":true,"parentId":"3","id":"5"},"6":{"path":"/data","name":"数据采集","icon":"database","parentId":"2","id":"6"},"7":{"path":"/data/list","name":"数据列表","parentId":"6","id":"7"},"8":{"path":"/data/visualization","name":"数据可视化","parentId":"6","id":"8"},"9":{"path":"/data/detail/:id","name":"数据详情","hideInMenu":true,"parentId":"6","id":"9"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__login__index" */'@/pages/login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__layouts__BasicLayout" */'@/pages/layouts/BasicLayout.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__device__list__index" */'@/pages/device/list/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__device__control__index" */'@/pages/device/control/index.tsx')),
'6': React.lazy(() => import('./EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__data__list__index" */'@/pages/data/list/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__data__visualization__index" */'@/pages/data/visualization/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__data__detail__index" */'@/pages/data/detail/index.tsx')),
},
  };
}
